API_ID = 21252171
API_HASH = "485e5fec9f6090c7c0f461ab19bb5140"
SESSION_NAME = "my_session"

PINECONE_API_KEY="pcsk_3ynGce_QDwtvEJopBEtLD3fzetwXX5YBV5Ymj1UK5TmuGeYtAjVAPVWVLYW4qum8F7YyVJ"
PINECONE_ENVIRONMENT="us-east-1"
PINECONE_INDEX_NAME="sebi-flag-data"
PINECONE_INDEX_NAME_HISTORY="sebi-flag-data-history"
PINECONE_INDEX_NAME_MONEYCONTROL="sebi-money-control-data"
PINECONE_INDEX_NAME_CHITORGARH="sebi-chittorgarh-data"

REDDIT_CLIENT_ID = "icZXMv6zitIdeLH4mhbwlA"
REDDIT_CLIENT_SECRET = "N8-DBBE8gX9N8auGSboP_fqFYr0xiA"
REDDIT_USER_AGENT = "SEBI Hackathon v0.1"

YOUTUBE_API_KEY = "AIzaSyC7RO71lyEh2K7cIVzZ8N5QK7TDby8C0QQ"

OPENAI_API_KEY="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"  # Get from https://platform.openai.com/account/api-keys
