API_ID = 21252171
API_HASH = "485e5fec9f6090c7c0f461ab19bb5140"
SESSION_NAME = "my_session"

PINECONE_API_KEY="pcsk_3ynGce_QDwtvEJopBEtLD3fzetwXX5YBV5Ymj1UK5TmuGeYtAjVAPVWVLYW4qum8F7YyVJ"
PINECONE_ENVIRONMENT="us-east-1"
PINECONE_INDEX_NAME="sebi-flag-data"
PINECONE_INDEX_NAME_HISTORY="sebi-flag-data-history"
PINECONE_INDEX_NAME_MONEYCONTROL="sebi-money-control-data"
PINECONE_INDEX_NAME_CHITORGARH="sebi-chittorgarh-data"

REDDIT_CLIENT_ID = "icZXMv6zitIdeLH4mhbwlA"
REDDIT_CLIENT_SECRET = "N8-DBBE8gX9N8auGSboP_fqFYr0xiA"
REDDIT_USER_AGENT = "SEBI Hackathon v0.1"

YOUTUBE_API_KEY = "AIzaSyC7RO71lyEh2K7cIVzZ8N5QK7TDby8C0QQ"

OPENAI_API_KEY="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"  # Get from https://platform.openai.com/account/api-keys
