API_ID = 21252171
API_HASH = "485e5fec9f6090c7c0f461ab19bb5140"
SESSION_NAME = "my_session"

PINECONE_API_KEY="pcsk_3ynGce_QDwtvEJopBEtLD3fzetwXX5YBV5Ymj1UK5TmuGeYtAjVAPVWVLYW4qum8F7YyVJ"
PINECONE_ENVIRONMENT="us-east-1"
PINECONE_INDEX_NAME="sebi-flag-data"
PINECONE_INDEX_NAME_HISTORY="sebi-flag-data-history"
PINECONE_INDEX_NAME_MONEYCONTROL="sebi-money-control-data"
PINECONE_INDEX_NAME_CHITORGARH="sebi-chittorgarh-data"